[default.security]
ALGORITHM = "HS256"

[default.server]
port = 8000
host = "127.0.0.1"
log_level = "info"
reload = false

[development.db]
echo = true

[development.server]
log_level = "debug"
reload = true
cors_origins = ["http://localhost:3000", "http://localhost:4200"]

[production.db]
echo = false

[production.server]
log_level = "error"
reload = false

[testing]
dynaconf_merge = true

[testing.server]
cors_origins = ["http://localhost:3000", "http://localhost:4200"]